### ISSUE TITLE
[1.18.2] ClassNotFoundException on Fabric/Quilt (LootSupplierBuilderHooks)

### ISSUE THREAD

**Issue by paulhlschr** [ValleyCraft-Dev-Team/valleycraft-old#60]
The game crashes due to a ClassNotFoundException related to `net.fabricmc.fabric.mixin.loot.table.LootSupplierBuilderHooks`.
The crash occurs when creating or joining a single-player world.

### Reproducible?
✅ Yes.
### Minecraft Version
1.18.2
### Mod Loader Version
Quilt Loader 0.17.0-beta.2
### Mod Versions
- ValleyCraft 2.3-1.18.2
- Cloth Config 6.2.57
- Quilted Fabric API 1.0.0-beta.17+0.54.0-1.18.2
### Log File
[latest.log](https://github.com/ValleyCraft-Dev-Team/ValleyCraft/files/8837427/latest.log)

### Reproducible?
✅ Yes.
### Minecraft Version
1.18.2
### Mod Loader Version
- Fabric Loader 0.14.6
- Intermediary Mappings 1.18.2
### Mod Versions
- ValleyCraft 2.3-1.18.2
- Cloth Config 6.2.57
- Fabric API 0.54.0-1.18.2
### Log File
[latest.log](https://github.com/ValleyCraft-Dev-Team/ValleyCraft/files/8837441/latest.log)

**Comment by Jamalam360** [comment]
I also have [a similar issue](https://hst.sh/evifavedad.md)

**Comment by LiviiYS** [comment]
Exact same issue with loot tables on fabric

**Comment by 404Mate** [comment]
for now this can be solved by downgrading fabric api to v53

**Comment by itsdinkd** [comment]
> for now this can be solved by downgrading fabric api to v53

not a solution when you need to update mods for a modpack.


```java
[15:45:48] [Render thread/WARN]: Failed to load datapacks, can't proceed with server load
java.util.concurrent.ExecutionException: java.lang.NoClassDefFoundError: net/fabricmc/fabric/mixin/loot/table/LootSupplierBuilderHooks
	at Not Enough Crashes deobfuscated stack trace.(1.18.2+build.3) ~[?:?]
	at java.util.concurrent.CompletableFuture.reportGet(CompletableFuture.java:396) ~[?:?]
	at java.util.concurrent.CompletableFuture.get(CompletableFuture.java:2073) ~[?:?]
	at net.minecraft.client.MinecraftClient.createSaveLoader(MinecraftClient:2124) ~[?:?]
	at net.minecraft.client.MinecraftClient.startIntegratedServer(MinecraftClient:1972) ~[?:?]
	at net.minecraft.client.MinecraftClient.startIntegratedServer(MinecraftClient:1937) ~[?:?]
	at net.minecraft.client.gui.screen.world.WorldListWidget$Entry.start(WorldListWidget:431) ~[?:?]
	at net.minecraft.client.gui.screen.world.WorldListWidget$Entry.play(WorldListWidget:340) ~[?:?]
	at net.minecraft.client.gui.screen.world.WorldListWidget$Entry.mouseClicked(WorldListWidget:271) ~[?:?]
	at net.minecraft.client.gui.widget.EntryListWidget.mouseClicked(EntryListWidget:359) ~[?:?]
	at net.minecraft.client.gui.ParentElement.mouseClicked(ParentElement:27) ~[?:?]
	at net.minecraft.client.Mouse.method_1611(Mouse:94) ~[?:?]
	at net.minecraft.client.gui.screen.Screen.wrapScreenError(Screen:492) ~[?:?]
	at net.minecraft.client.Mouse.onMouseButton(Mouse:94) ~[?:?]
	at net.minecraft.client.Mouse.method_22686(Mouse:165) ~[?:?]
	at net.minecraft.util.thread.ThreadExecutor.execute(ThreadExecutor:103) ~[?:?]
	at net.minecraft.client.Mouse.method_22684(Mouse:165) ~[?:?]
	at org.lwjgl.glfw.GLFWMouseButtonCallbackI.callback(GLFWMouseButtonCallbackI.java:36) ~[lwjgl-glfw-3.2.2.jar:?]
	at org.lwjgl.system.JNI.invokeV(Native Method) ~[lwjgl-3.2.2.jar:?]
	at org.lwjgl.glfw.GLFW.glfwWaitEventsTimeout(GLFW.java:3174) ~[lwjgl-glfw-3.2.2.jar:?]
	at com.mojang.blaze3d.systems.RenderSystem.limitDisplayFPS(RenderSystem:222) ~[client-intermediary.jar:?]
	at net.minecraft.client.MinecraftClient.render(MinecraftClient:1150) ~[?:?]
	at net.minecraft.client.MinecraftClient.run(MinecraftClient:737) ~[?:?]
	at net.minecraft.client.main.Main.main(Main:236) [client-intermediary.jar:?]
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:460) [fabric-loader-0.14.6.jar:?]
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74) [fabric-loader-0.14.6.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23) [fabric-loader-0.14.6.jar:?]
Caused by: java.lang.NoClassDefFoundError: net/fabricmc/fabric/mixin/loot/table/LootSupplierBuilderHooks
	at io.github.linkle.valleycraft.utils.loot.LootTableHelper.onLootLoad(LootTableHelper.java:39) ~[valley-craft-2.3-1.18.2.jar:?]
	at net.fabricmc.fabric.api.loot.v1.event.LootTableLoadingCallback.lambda$static$0(LootTableLoadingCallback.java:47) ~[fabric-loot-tables-v1-1.1.0+e747827960-a0206e3811f2605a.jar:?]
	at net.fabricmc.fabric.impl.loot.table.LootTablesV1Init.lambda$onInitialize$1(LootTablesV1Init.java:40) ~[fabric-loot-tables-v1-1.1.0+e747827960-a0206e3811f2605a.jar:?]
	at net.fabricmc.fabric.api.loot.v2.LootTableEvents.lambda$static$0(LootTableEvents.java:39) ~[fabric-loot-api-v2-1.0.0+e747827960-9baec74ea7067568.jar:?]
	at net.minecraft.loot.LootManager.mdff5ad4$lambda$apply$0$2(LootManager:1067) ~[?:?]
	at com.google.common.collect.RegularImmutableMap.forEach(RegularImmutableMap.java:196) ~[guava-31.0.1-jre.jar:?]
	at net.minecraft.loot.LootManager.handler$gde000$apply(LootManager:1055) ~[?:?]
	at net.minecraft.loot.LootManager.apply(LootManager:59) ~[?:?]
	at net.minecraft.loot.LootManager.apply(LootManager:17) ~[?:?]
	at net.minecraft.resource.SinglePreparationResourceReloader.method_18790(SinglePreparationResourceReloader:13) ~[?:?]
	at java.util.concurrent.CompletableFuture$UniAccept.tryFire(CompletableFuture.java:718) ~[?:?]
	at java.util.concurrent.CompletableFuture$Completion.run(CompletableFuture.java:482) ~[?:?]
	at net.minecraft.resource.SimpleResourceReload.method_18365(SimpleResourceReload:69) ~[?:?]
	at net.minecraft.util.thread.ThreadExecutor.executeTask(ThreadExecutor:157) ~[?:?]
	at net.minecraft.util.thread.ReentrantThreadExecutor.executeTask(ReentrantThreadExecutor:23) ~[?:?]
	at net.minecraft.util.thread.ThreadExecutor.runTask(ThreadExecutor:131) ~[?:?]
	at net.minecraft.util.thread.ThreadExecutor.runTasks(ThreadExecutor:140) ~[?:?]
	at net.minecraft.client.MinecraftClient.createSaveLoader(MinecraftClient:2123) ~[?:?]
	... 23 more
Caused by: java.lang.ClassNotFoundException: net.fabricmc.fabric.mixin.loot.table.LootSupplierBuilderHooks
	at jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:641) ~[?:?]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:520) ~[?:?]
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.loadClass(KnotClassDelegate.java:226) ~[fabric-loader-0.14.6.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotClassLoader.loadClass(KnotClassLoader.java:145) ~[fabric-loader-0.14.6.jar:?]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:520) ~[?:?]
	at io.github.linkle.valleycraft.utils.loot.LootTableHelper.onLootLoad(LootTableHelper.java:39) ~[valley-craft-2.3-1.18.2.jar:?]
	at net.fabricmc.fabric.api.loot.v1.event.LootTableLoadingCallback.lambda$static$0(LootTableLoadingCallback.java:47) ~[fabric-loot-tables-v1-1.1.0+e747827960-a0206e3811f2605a.jar:?]
	at net.fabricmc.fabric.impl.loot.table.LootTablesV1Init.lambda$onInitialize$1(LootTablesV1Init.java:40) ~[fabric-loot-tables-v1-1.1.0+e747827960-a0206e3811f2605a.jar:?]
	at net.fabricmc.fabric.api.loot.v2.LootTableEvents.lambda$static$0(LootTableEvents.java:39) ~[fabric-loot-api-v2-1.0.0+e747827960-9baec74ea7067568.jar:?]
	at net.minecraft.loot.LootManager.mdff5ad4$lambda$apply$0$2(LootManager:1067) ~[?:?]
	at com.google.common.collect.RegularImmutableMap.forEach(RegularImmutableMap.java:196) ~[guava-31.0.1-jre.jar:?]
	at net.minecraft.loot.LootManager.handler$gde000$apply(LootManager:1055) ~[?:?]
	at net.minecraft.loot.LootManager.apply(LootManager:59) ~[?:?]
	at net.minecraft.loot.LootManager.apply(LootManager:17) ~[?:?]
	at net.minecraft.resource.SinglePreparationResourceReloader.method_18790(SinglePreparationResourceReloader:13) ~[?:?]
	at java.util.concurrent.CompletableFuture$UniAccept.tryFire(CompletableFuture.java:718) ~[?:?]
	at java.util.concurrent.CompletableFuture$Completion.run(CompletableFuture.java:482) ~[?:?]
	at net.minecraft.resource.SimpleResourceReload.method_18365(SimpleResourceReload:69) ~[?:?]
	at net.minecraft.util.thread.ThreadExecutor.executeTask(ThreadExecutor:157) ~[?:?]
	at net.minecraft.util.thread.ReentrantThreadExecutor.executeTask(ReentrantThreadExecutor:23) ~[?:?]
	at net.minecraft.util.thread.ThreadExecutor.runTask(ThreadExecutor:131) ~[?:?]
	at net.minecraft.util.thread.ThreadExecutor.runTasks(ThreadExecutor:140) ~[?:?]
	at net.minecraft.client.MinecraftClient.createSaveLoader(MinecraftClient:2123) ~[?:?]
	... 23 more
[16:10:58] [CullThread/INFO]: [STDOUT]: Shutting down culling task!
[16:10:58] [Render thread/INFO]: Stopping!
[16:10:58] [Render thread/WARN]: Adding dml-refabricated:depth_strider to saved/remote registry.
[16:10:58] [Render thread/WARN]: Adding dml-refabricated:underwater_haste to saved/remote registry.
[16:10:58] [Render thread/WARN]: Adding creeperspores:creeper_spore to saved/remote registry.
[16:10:58] [Render thread/INFO]: closing rrp artis:resources
[16:10:58] [Render thread/INFO]: closing rrp carrier:gloves
[16:10:58] [Render thread/INFO]: closing rrp minecraft:phonos_data
[16:10:58] [Render thread/INFO]: closing rrp secretrooms:secret_rooms_data
[16:10:58] [Render thread/INFO]: closing rrp minecraft:phonos_assets
[16:10:58] [Render thread/INFO]: closing rrp secretrooms:secret_rooms_assets
[16:10:58] [CraftPresence-ShutDown-Handler/INFO]: Shutting down CraftPresence...

``` 

Once fixed please let me know and I will add back ValleyCraft into Another Quality Modpack 2

**Comment by AndEditor7** [comment]
It's now fixed in the latest update.
